### ISSUE TITLE
Change to callback parameters in 1.2 is backwards-incompatible

### ISSUE THREAD

**Issue by halostatue** [soveran/micromachine#26]
This is probably a very rare case, but the change in fc9635c is not compatible with the previous version and *could* result in failures.

The code below demonstrates:

```ruby
require 'micromachine'

class CallbackBug
  def initialize
    @fsm = MicroMachine.new(:new).tap do |fsm|
      fsm.when(:first,  new: :first_stage)
      fsm.when(:second, first_stage: :second_stage)

      fsm.on(:first_stage, &method(:first_stage))
      fsm.on(:second_stage, &method(:second_stage))

      fsm.on(:any) do |event|
        puts "Event #{event} => #{@fsm.state}"
      end
    end
  end

  def run
    @fsm.trigger!(:first)
    @fsm.trigger!(:second)
  end

  private

  def first_stage(event)
    p event
  end

  def second_stage
  end
end

CallbackBug.new.run
```

The output of this is:

```
:first
Event first => first_stage
ArgumentError: wrong number of arguments (1 for 0)
from (pry):28:in `second_stage'
```

**Comment by soveran** [comment]
Hey @halostatue, great to see you here! A quick question first, did you run into this problem? Or is it just the good eye of an old time rubyist? I'd like to know how urgent it is for you to get this fixed, because I usually take very long times to modify a library. If it broke something for you, I can consider reverting the breaking change in the meantime. Let me know, and thanks a lot for reporting this.

**Comment by halostatue** [comment]
Just the mark 1 eyeball, with contact lens accessory. :)

This is not urgent, but I also have a fix ready for you with #27. (I was going to put this as a comment originally for that PR, but I decided that the bug is worth reporting independently of the change.)

**Comment by soveran** [comment]
Excellent! Great catch, thanks a lot for reporting the issue. I will check the pull request and I guess I'll continue the conversation there.

**Comment by halostatue** [comment]
With the release of 2.0, this is not really relevant as the change in API can be expected.
