### ISSUE TITLE
Add `#triggerable_events` method?

### ISSUE THREAD

**Issue by nathanl** [soveran/micromachine#36]
MicroMachine exposes an `events` method, which lists all events that may be possible at any time. But only a subset of those can be triggered from a given state.

In an application it's sometimes useful to present that subset to users. For instance, if a post is in "draft" status, display buttons to trigger `:publish` or `:archive`, but not to `:unpublish`.

I'm using this code to find triggerable events:

```ruby
sm.transitions_for.keys.select { |event| sm.trigger?(event) }
```

Might this be worth adding to MicroMachine itself?

**Comment by soveran** [comment]
Sounds good. Looping through all the events looks inefficient, but maybe it's the best implementation we can currently have. We could keep another hash with the mapping from states to events, which would give us faster access to the list of available events at the cost of memory and hash updates. In any case, we can start with this implementation and see how it goes, because we can change it at any point in the future. What could be a sensitive name? While trying it locally, I called it `available_events`, but maybe there's a better one (I couldn't find anything relevant at https://en.wikipedia.org/wiki/Finite-state_machine).

**Comment by nathanl** [comment]
`triggerable_events` is the name I used, since I'm checking `trigger?` for each one. How does that sound?

I don't think looping through all the events is a big deal. A huge state machine might have 100 possible events. Calling `trigger?` for each one is a single operation to check for a hash key, which is `O(1)`, so looping through the events is the bottleneck.

I just did a quick test script and looped through a hash with 1,000 keys.

```ruby
require "time"
num_hash = Hash[(1..1_000).map {|i| [i, i.to_s]}]
start_time = Time.now
num_hash.select {|k, v| k % 2 == 0 }
end_time = Time.now
puts "took #{end_time - start_time}"
```

This took `0.000154` seconds. :) For a typical machine with maybe 10 events, nobody will ever give it a thought, and the complexity of caching anything would not be worth it. If anybody has 100,000 events and this isn't fast enough, tell them to fork it and run away screaming. 😆

**Comment by nathanl** [comment]
Maybe I'm being too flippant; somebody may be running this same check for many items in the same web request. But I still think that, as you said, let's start simple and optimize if a need arises.

Sounds like you already started this feature. Do you want to do it, or would you rather I give it a try?

**Comment by nathanl** [comment]
By the way, I realized after opening this that `sm.transitions_for.keys` in my example should have been `sm.events`.

**Comment by soveran** [comment]
Yes, let's call it `triggerable_events`. I had this implementation, based on yours:

```ruby
def triggerable_events
  events.select { |event| trigger?(event) }
end
```

And the accompanying test in `test/introspection.rb`:

```ruby
test "list the available events for the current state" do |machine|
  assert_equal [:confirm, :ignore], machine.available_events
end
```

Do you want to send me a pull request with these changes?

**Comment by nathanl** [comment]
Sure. :)

**Comment by nathanl** [comment]
Done.
